<?php


namespace frontend\controllers;


use common\models\Category;
use common\models\Images;
use yii\web\Controller;
use Yii;
class ProductListController extends CommonController
{

    /**
     * 通过url转换，定位到对应的ControllerID，这样的话就不用每个  /url/  都写一个Controller
     */
    public function init()
    {
        $url = Yii::$app->request->url;
        $arr = explode("/", "$url");
        $this->id = $arr[1];
        parent::init(); // TODO: Change the autogenerated stub

    }

    function actionIndex(){
        parent::common();
        Yii::$app->params['nav_list'] = Category::find()->where(['pid' => Yii::$app->params['lanmu']['pid']])->all();//研发制造下面所有的分类
        $this->data['list'] = Images::find()->where(['category_id2'=>Yii::$app->params['lanmu']['id']]);
        return $this->render('/product/list-tz',['data'=>$this->data]);
    }


}