<?php


namespace frontend\controllers;


use common\models\Category;
use common\models\Images;
use yii\web\Controller;
use Yii;
class ZhuantiController extends CommonController
{

    /**
     * 通过url转换，定位到对应的ControllerID，这样的话就不用每个  /url/  都写一个Controller
     */
    public function init()
    {
        $url = Yii::$app->request->url;
        $arr = explode("/", "$url");
        $this->id = $arr[1];
        parent::init(); // TODO: Change the autogenerated stub

    }

    function actionIndex(){
        parent::common();

        return $this->render('/zhuanti/diwenzt',['data'=>$this->data]);
    }


}