<?php


namespace frontend\controllers;


use common\models\Category;
use common\models\Images;
use yii\web\Controller;
use Yii;
class ZhuantiController extends CommonController
{

    /**
     * 通过url转换，定位到对应的ControllerID，这样的话就不用每个  /url/  都写一个Controller
     */
    public function init()
    {
        $url = Yii::$app->request->url;
        $arr = explode("/", "$url");
        $this->id = $arr[1];
        parent::init(); // TODO: Change the autogenerated stub

    }

    function actionIndex(){
        parent::common();
        $this->view->params['meta_title']="低温三元锂电池,低温磷酸铁锂电池生产厂家";

        $this->view->params['keywords']="电池,LARGE品牌,-40℃ 0.2C充电,-50℃放电容量≥75%.";

        $this->view->params['description']="东莞市钜大电子有限公司,". Yii::$app->params['year']."年低温锂电池生产厂家,按需定制低温放电/低温充放电/低温过针刺/低温高能量密度/低温高倍率锂";

        return $this->render('/zhuanti/diwenzt',['data'=>$this->data]);
    }


}